local mod = "SUPER"
local terminal = "kitty"

hl.config({ autogenerated = false })

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})

hl.monitor({
    output = "DVI-D-2",
    mode = "preferred",
    position = "auto-left",
    scale = 1,
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "preferred",
    position = "auto-right",
    scale = 1,
})

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("awww-daemon")
end)

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 2,
        layout = "master",
        col = {
            active_border = {
                colors = { "rgba(33ccffee)", "rgba(00ff99ee)" },
                angle = 45,
            },
        },
    },
    master = {
        new_status = "master",
    },
    input = {
        kb_layout = "us, de",
        kb_options = "caps:swapescape, altwin:swap_alt_win",
        repeat_rate = 50,
        repeat_delay = 300,
        touchpad = {
            natural_scroll = false,
        },
    },
    misc = {
        enable_swallow = true,
        swallow_regex = "^(kitty)$",
        swallow_exception_regex = "^(?!zathura|xournalpp).*",
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

hl.device({
    name = "wacom-intuos-pt-s-pen",
    output = "DVI-D-1",
})

hl.bind(mod .. " + SHIFT + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mod .. " + P", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mod .. " + SHIFT + C", hl.dsp.window.close())
hl.bind(mod .. " + CTRL + delete", hl.dsp.exit())
hl.bind(mod .. " + SHIFT + End", hl.dsp.exec_cmd("systemctl poweroff"))
hl.bind(mod .. " + Q", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mod .. " + S", hl.dsp.exec_cmd("hyprctl switchxkblayout current next"))
hl.bind(mod .. " + SHIFT + S", hl.dsp.window.toggle_swallow())
hl.bind(mod .. " + W", hl.dsp.exec_cmd("chromium --disable-gpu-compositing"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd(terminal .. " -e wiremix"))
hl.bind("Print", hl.dsp.exec_cmd("grimblast copy area"))

hl.bind(mod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mod .. " + SHIFT + M", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
hl.bind(mod .. " + F", hl.dsp.window.float({ action = "toggle" }))

hl.bind(mod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))

hl.bind(mod .. " + SHIFT + comma", hl.dsp.workspace.move({ monitor = "left" }))
hl.bind(mod .. " + SHIFT + period", hl.dsp.workspace.move({ monitor = "right" }))

for workspace = 1, 9 do
    local keycode = "code:1" .. (workspace - 1)
    hl.bind(mod .. " + " .. keycode, hl.dsp.focus({ workspace = workspace }))
    hl.bind(mod .. " + SHIFT + " .. keycode, hl.dsp.window.move({ workspace = workspace }))
end

local repeating = {
    locked = true,
    repeating = true,
}

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 1%+"), repeating)
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 1%-"), repeating)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), repeating)
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), repeating)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), repeating)
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), repeating)

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
