# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-dd4c663b-fb93-4754-b19d-9dd5f44fd5c3".device =
    "/dev/disk/by-uuid/dd4c663b-fb93-4754-b19d-9dd5f44fd5c3";
  boot.initrd.luks.devices."luks-c1a3d35b-2467-4eb3-aa4c-3b5b97b9298d".device =
    "/dev/disk/by-uuid/c1a3d35b-2467-4eb3-aa4c-3b5b97b9298d";

  fileSystems."/" = {
    device = "/dev/mapper/luks-dd4c663b-fb93-4754-b19d-9dd5f44fd5c3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BB5E-5529";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-c1a3d35b-2467-4eb3-aa4c-3b5b97b9298d"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
